"""empty message

Revision ID: db48a7c4fd52
Revises: 46567c2c0a72
Create Date: 2021-11-29 17:49:29.531933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db48a7c4fd52'
down_revision = '46567c2c0a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('access_token_expiration', sa.DateTime(), nullable=True),
    sa.Column('refresh_token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('pelm_user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pelm_user_id')
    op.drop_table('tokens')
    # ### end Alembic commands ###
